### ISSUE TITLE
Docker hub issue - docker pull command only works with release tag

### ISSUE THREAD

**Issue by decirella** [BitCurator/bitcurator-docker#3]
The docker pull command, as shown on the docker hub, results in the following error
$ docker pull bitcurator/bitcurator
Using default tag: latest
Error response from daemon: manifest for bitcurator/bitcurator:latest not found: manifest unknown: manifest unknown

The following command with the release tag added was successful:
$ docker pull bitcurator/bitcurator:v4.2.1

**Comment by kamwoods** [comment]
Will add a "latest" tag to the next release to resolve this.

**Comment by kamwoods** [comment]
Fixed in most recent tagged release, v4.4.0.
